sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: WZ9XZf+P5y4S8RXjTPp2q+UPd2aGGS9ug8swUsDwt4x7edXiHmLy+0IkYKHEkHy9sP2hmDDG4fp2E5qvmFPWkRGM21fGcUlY9pwEX8VBnErFzOGOymCqn6hYs7PljL90T2D6lAgPJMYcp4nJM+Tv25yxN3PG45Xqmp8JmAdHiri9jUUPyWTMNEFNu//TzXiQxxxXwJwjTyvNfQQW6MLhiYSR3dZcMHRxjjdhmnPPwXl5E32zBDZajGxnbnmpZycKBZAN6e5qr4N0m9TCDps69ebAqRU8IXbE4/cDGR48PZYUeASNVS9Trlq5eoybZR9QFXNxWVE73WEd6RCjTetMS6+rgnVySXUXqFpTMTYJPsA7o05N9OzoFtQOok7ISv6saqZCEnsU+TZ5cKp3MTjRe89+YNkYZDmPCA0oJTrI8Tj1tuA6IzrLLMMmm4Y1DYjo+FYCtuR3imqz0lC9rww736cRVzK7aTnyAuvOv5/R5bRncKNCkORD3jG3qLrdsS2TOUMWFP95jOpemKYtnfFPaAu7yzYK2/SmCYG9K9RPBb7QSUuzMOo5rPKg/TWpTbmmAj1KmVwfiu9TWSdWiDuvxfZlPSphCNmidph5A5HBmv5jhkgQDaJa4MzY0lBYMfZaBfC5+g94bPJis5GYuzYBk5GtciglqMetCj4hQe69HBg=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: FCLSgpNOCpzl1reQXt3CdA/qK058MK5WGSqN0MwcU9vzjlVtnYQAk0zA26UpAUUcchkHLw1x81ftXUBSL7M3qsYWl9qLhfuBJbpfx0OtrGmS7RbH2W0BOj1iTfagSIXNSNM7ZRgp8HshuhXQPFMz3tWd1TJBNS6vUnZrkB68QLnlcs+N56bJuI7qQ3CDF2FXJex+2T7GG8Wp6QeKlsotkiexdxWhTBhEAssn8kQKZsQqfbDcv5NCB08sZwQs1OOVUOKKZHFqgk4x/yfaAsagtPHyd4pztz7zzTpPNIjgE1ycEpUgzETldWzs0CIrx8Mi4G+muzTDn73oQ9oMJ2D1d09v5IL99z/cPwi7SzLdJH0/LxdOj2hQAas0sMvWQk7OMae+7jH5YozpQdY4aR3CgZ/EHFxslPX1ujmdpYImnaGX6fq2qkd3aKhjYcS4mZCFo8hLe6sGEvtgauhPavOjCEL9pt8GOtE2uOI00qG1rFAZ/uA8HmMSU++MGvwvl5HcYabE2aheHHV1K93XYPzOkU3Hjg0R8soH0xZighQIHfcOGpXmZ0M5iV6TfV1lXNbWFoHVWpYD3IulIo0+gQEsfHJj4AUsZhkE4ye04/MDf/4R0pMiIC2oYNGVvRG9f6kCLFdJo9Gmg2uF9P1LhCVlT2zkpzyeHEvuGIaod20VbaU=
